version: '3.7'

services:
    php:
        build:
            context: ./config/docker/local/php
            args:
                - HOST_UID=${HOST_UID}
        image: e-shop-analytics-php
        container_name: e-shop-analytics-php
        networks:
            net:
                aliases:
                    - e-shop-analytics-php
            local:
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/local/php/docker-entrypoint.sh
        environment:
            - COMPOSER_HOME=/var/www/html/var/composer
            - PHP_IDE_CONFIG
            - APP_ENV
    nginx:
        build: ./config/docker/local/nginx
        image: e-shop--nginx
        container_name: e-shop-analytics-nginx
        networks:
            net:
                aliases:
                    - e-shop-analytics-nginx
            local:
        depends_on:
            - php
        ports:
            - "${SERVER_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    clickhouse:
        image: yandex/clickhouse-server
        container_name: e-shop-analytics-clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        networks:
            - local
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - clickhouse:/var/lib/clickhouse
            - clickhouse-config:/etc/clickhouse-server
    postgres:
        image: postgres:11.7
        container_name: e-shop-analytics-postgres
        networks:
            - local
        ports:
            - "${EXTERNAL_POSTGRES_PORT}:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: e-shop-analytics-zookeeper
        networks:
            - net
            - local
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        container_name: e-shop-analytics-kafka
        networks:
            net:
                aliases:
                    - e-shop-analytics-kafka
            local:
        ports:
            - "9092:9092"
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=e-shop-analytics-kafka
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_PORT=9092
    tabix:
        image: spoonest/clickhouse-tabix-web-client
        container_name: e-shop-analytics-tabix
        ports:
            - "${TABIX_HTTP_PORT}:80"
        environment:
            - CH_HOST=clickhouse:8123
volumes:
    clickhouse:
        name: e-shop-analytics-clickhouse
    clickhouse-config:
        name: e-shop-analytics-clickhouse-config
    postgres:
        name: e-shop-analytics-postgres
networks:
    net:
        name: e-shop-net
    local:
        name: e-shop-analytics-local
