version: '3.7'

services:
    php:
        build:
            context: ./config/docker/local/php
            args:
                - HOST_UID=${HOST_UID}
        image: e-shop-analytics-php
        container_name: e-shop-analytics-php
        networks:
            net:
                aliases:
                    - e-shop-analytics-php
            local:
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/local/php/docker-entrypoint.sh
        environment:
            - COMPOSER_HOME=/var/www/html/var/composer
            - PHP_IDE_CONFIG
            - APP_ENV
    nginx:
        build: ./config/docker/local/nginx
        image: e-shop--nginx
        container_name: e-shop-analytics-nginx
        networks:
            net:
                aliases:
                    - e-shop-analytics-nginx
            local:
        depends_on:
            - php
        ports:
            - "${SERVER_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    clickhouse:
        image: yandex/clickhouse-server
        container_name: e-shop-analytics-clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        networks:
            - local
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - clickhouse:/var/lib/clickhouse
volumes:
    clickhouse:
        name: e-shop-analytics-clickhouse
networks:
    net:
        name: e-shop-net
    local:
        name: e-shop-analytics-local
