parameters:
    api_urls: ^/api
    kafka:
        host: '%env(KAFKA_HOST)%'
        port: '%env(KAFKA_PORT)%'
        group: '%env(KAFKA_GROUP)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Analytics/Entity,Infrastructure/Migrations,Infrastructure/Framework/Symfony/Kernel.php}'

    App\Infrastructure\EventListener\Doctrine\PostgresqlSchemeFix:
        tags:
            - { name: doctrine.event_subscriber, connection: postgres }

    App\Infrastructure\Kafka\RdKafkaProducer:
        arguments:
            $kafkaParams: '%kafka%'

    App\Analytics\Repository\ClickHouseFactSaleRepository:
        arguments:
            $connection: '@doctrine.dbal.clickhouse_connection'

    App\Analytics\Repository\PostgresFactSaleRepository:
        arguments:
            $connection: '@doctrine.dbal.postgres_connection'

    App\Analytics\Repository\FactSaleRepositoryInterface: '@App\Analytics\Repository\ClickHouseFactSaleRepository'
#    App\Analytics\Repository\FactSaleRepositoryInterface: '@App\Analytics\Repository\PostgresFactSaleRepository'